apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80            # The port that the service will expose
      targetPort: 8080
      nodePort: 30007    # The port on the container that the service will forward traffic to
         # The port on the node that will be exposed (should be in the range 30000-32767)

