apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapp-frontend
  labels:
    app: wapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wapp
      tier: frontend
  template:
    metadata:
      labels:
        app: wapp
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: simalguven/frontend-image2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapp-backend
  labels:
    app: wapp
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wapp
      tier: backend
  template:
    metadata:
      labels:
        app: wapp
        tier: backend
    spec:
      containers:
      - name: backend
        image: simalguven/backend-image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: wapp
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: wapp
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
