kubectl apply -f complex-frontend-deployment-no-autoscaling.yaml 
kubectl apply -f complex-backend-deployment-no-autoscaling.yaml 
kubectl apply -f complex-app-different-pods-ingress.yaml 
kubectl apply -f complex-app-different-pods-service.yaml 
kubectl apply -f complex-frontend-hpa.yaml 
kubectl apply -f complex-backend-hpa.yaml 
kubectl apply -f ingress-nginx-nodeport.yaml 
kubectl delete hpa complex-frontend-hpa
kubectl delete hpa complex-backend-hpa