apiVersion: v1
kind: Service
metadata:
  name: complex-app-service
spec:
  selector:
    app: complex-frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: complex-backend-service
spec:
  selector:
    app: complex-backend
  ports:
    - name: backend
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
