apiVersion: apps/v1
kind: Deployment
metadata:
  name: complex-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complex-backend
  template:
    metadata:
      labels:
        app: complex-backend
    spec:
      containers:
        - name: complex-backend
          image: hasanseker/complex-backend:v2
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
