apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: complex-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /frontend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: complex-app-service
                port:
                  number: 80
          - path: /backend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: complex-backend-service
                port:
                  number: 3000
