vagrant scp complex-frontend-deployment-autoscaling.yaml controlplane:/home/vagrant/
vagrant scp complex-frontend-deployment-no-autoscaling.yaml controlplane:/home/vagrant
vagrant scp complex-backend-deployment-autoscaling.yaml controlplane:/home/vagrant/
vagrant scp complex-backend-deployment-no-autoscaling.yaml controlplane:/home/vagrant
vagrant scp complex-app-different-pods-ingress.yaml controlplane:/home/vagrant/
vagrant scp complex-app-different-pods-service.yaml controlplane:/home/vagrant/
vagrant scp complex-frontend-hpa.yaml controlplane:/home/vagrant
vagrant scp complex-backend-hpa.yaml controlplane:/home/vagrant
vagrant scp ingress-nginx-nodeport.yaml controlplane:/home/vagrant/
vagrant scp controlplane.sh controlplane:/home/vagrant/
vagrant scp worker.sh node01:/home/vagrant/
vagrant scp apply-no-autoscaling.sh controlplane:/home/vagrant/
vagrant scp apply-autoscaling.sh controlplane:/home/vagrant/