apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "pytime.local"
    http:
      paths:
      - path: /time
        pathType: Prefix
        backend:
          service:
            name: timeservice
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pytime
            port:
              number: 8081

